Feature/aggregations
apinf/emq-analytics-dashboard pull request #7
Opened 2017-03-06 14:37 UTC by frenchbread

2017-03-06 15:03 UTC, frenchbread commented
Please 👀

2017-03-07 09:26 UTC, bajiat commented
@Nazarah Can you comment from the UX point of view?

2017-03-07 10:13 UTC, brylie commented
@frenchbread can you give us some clearly defined metrics here? E.g. how many records is the dashboard loading? How much time (in milliseconds) do the following stages take (basically, what does the Chrome timeline contain)?

- data transfer
- ui paint

2017-03-07 10:13 UTC, brylie commented
Also, what do the performance metrics look like with 10x records? 100x?

2017-03-07 11:17 UTC, frenchbread commented
### Server side
The server side request to ES takes around `43-63` milliseconds.

<img width="464" alt="screen shot 2017-03-07 at 13 03 31" src="https://cloud.githubusercontent.com/assets/2122679/23654081/cf7beac4-0337-11e7-8104-c8da9c43ff90.png">

### Client side
On client side, the total page load takes around `2-2.5` seconds, and the actual rendering around `300` milliseconds.

![screen shot 2017-03-07 at 13 16 59](https://cloud.githubusercontent.com/assets/2122679/23654223/5d310890-0338-11e7-8aec-5ba59a9ca50e.png)

2017-03-07 11:24 UTC, brylie commented
Excellent, and how many records are you retrieving? That way we can figure out the relationship between the number of records and performance time.

2017-03-07 11:25 UTC, frenchbread commented
As of now the dataset that goes to the charts looks like this:

<img width="469" alt="screen shot 2017-03-07 at 13 18 50" src="https://cloud.githubusercontent.com/assets/2122679/23654299/b6d5a5c2-0338-11e7-95eb-bc4025812430.png">

So it does not really matter how much items are there since they are not grouped "manually" (by dc.js) but are pre-aggregated. The only load I can think of can come from selecting the maximum possible date range, e.g. years, decades? In that case the list of records will grow. Right now, by default, around 30 days (depending on a month) are shown.

I can go ahead & populate ES with more sample data, say for last 2+ years, and compare the results.

2017-03-07 11:26 UTC, brylie commented
Cool, yes. Keep in mind that the aggregation step takes time too.

2017-03-07 11:30 UTC, frenchbread commented
@brylie 

> Keep in mind that the aggregation step takes time too.

This is what "server-side" metric is.


Here is a range for all the data in the ES (1st Jan - 3rd Mar): 3069 items total. And it also takes from `40-60` ms to request data.

```
[{"key":"MQT connections over time","values":[{"x":1483308000000,"y":33},{"x":1483394400000,"y":107},{"x":1483480800000,"y":116},{"x":1483567200000,"y":46},{"x":1483653600000,"y":35},{"x":1483740000000,"y":72},{"x":1483826400000,"y":88},{"x":1483912800000,"y":68},{"x":1483999200000,"y":32},{"x":1484085600000,"y":48},{"x":1484172000000,"y":115},{"x":1484258400000,"y":47},{"x":1484344800000,"y":88},{"x":1484431200000,"y":20},{"x":1484517600000,"y":108},{"x":1484604000000,"y":41},{"x":1484690400000,"y":52},{"x":1484776800000,"y":101},{"x":1484863200000,"y":60},{"x":1484949600000,"y":96},{"x":1485036000000,"y":65},{"x":1485122400000,"y":42},{"x":1485208800000,"y":118},{"x":1485295200000,"y":106},{"x":1485381600000,"y":50},{"x":1485468000000,"y":92},{"x":1485554400000,"y":101},{"x":1485640800000,"y":93},{"x":1485727200000,"y":94},{"x":1485813600000,"y":43},{"x":1485900000000,"y":116},{"x":1485986400000,"y":24},{"x":1486072800000,"y":105},{"x":1486159200000,"y":80},{"x":1486245600000,"y":29},{"x":1486332000000,"y":72},{"x":1486418400000,"y":52},{"x":1486504800000,"y":116},{"x":1486591200000,"y":40},{"x":1486677600000,"y":67},{"x":1486764000000,"y":27},{"x":1486850400000,"y":86},{"x":1486936800000,"y":67},{"x":1487023200000,"y":0},{"x":1487109600000,"y":0},{"x":1487196000000,"y":0},{"x":1487282400000,"y":0},{"x":1487368800000,"y":0},{"x":1487455200000,"y":0},{"x":1487541600000,"y":0},{"x":1487628000000,"y":0},{"x":1487714400000,"y":0},{"x":1487800800000,"y":0},{"x":1487887200000,"y":0},{"x":1487973600000,"y":0},{"x":1488060000000,"y":0},{"x":1488146400000,"y":0},{"x":1488232800000,"y":0},{"x":1488319200000,"y":0},{"x":1488405600000,"y":0},{"x":1488492000000,"y":11}]}]
```

2017-03-07 11:34 UTC, brylie commented
Here is a revised diagram:

![screenshot_20170307_133407](https://cloud.githubusercontent.com/assets/17307/23654746/c6f86adc-033a-11e7-9dd9-4e970966325a.png)

From your understanding, what is the point I am trying to make here?

2017-03-07 11:37 UTC, brylie commented
Lets conduct a couple more **server-side aggregation** experiments, as mentioned above:

- 3,000 - 5,000 records
- 10,000 records
- 50,000 records
- 100,000

That way we can get more insight into how the *aggregation* step might vary as a function of the number of records.

2017-03-07 12:48 UTC, frenchbread commented
> From your understanding, what is the point I am trying to make here?

@brylie Isn't it, "measuring time aggregation takes"? Since aggregation is done on elasticsearch side, this metric is exposed in response object (`3` milliseconds in this case):

![screen shot 2017-03-07 at 14 47 15](https://cloud.githubusercontent.com/assets/2122679/23657076/178933fa-0345-11e7-99e9-1973bafa5a36.png)

2017-03-07 14:35 UTC, frenchbread commented
### Update

I've modified the server code and moved ElasticSearch client initialisation out of the Meteor method,  this was it also saves around `20` milliseconds more.

2017-03-08 08:25 UTC, brylie commented
> Since aggregation is done on elasticsearch side, search execution metric is exposed in the response object

Thanks for the example. Can we try a couple of experiments with larger data, say 10,000 or 50,000 record aggregation?

2017-03-08 12:44 UTC, frenchbread commented
@brylie I'm on it. 🚀

2017-03-08 16:03 UTC, frenchbread commented
Generated sample data & tested request/aggregation time, collected metrics & saved to `docs/request-aggregation-metrics.csv`

### Results

As seen in the CSV file, growing amount of analytics data for **fixed amount of days** (in this case 66 days ~ 2 months) does not slow down request/aggregation time. In fact, referring to numbers speed is even increasing:

| Items | Server -> ES request (ms) | ES search execution (ms) |
| ------ | ----------------------------------- | -------------------- |
| 13k | 42.9 | 3.9 |
| 20k | 30 | 3.7 |
| 50k | 28.7 | 2.3 |

2017-03-08 16:11 UTC, frenchbread commented
As of now, for this PR provided metrics is enough I suppose. I've created related issue #8 for testing within wider date ranges (larger amount of days).

2017-03-09 07:39 UTC, Nazarah commented
@frenchbread : great work done. I am really liking the simple look of chart here.
A few improvement suggestions:
* showing the metrics that we are meazuring in X-axis and Y-Axis along with units.
* It would have been great to remove the background grid from the graph so only the plot is seen. But if the graphs are built-in by default that way, we can skip it.

A few queries
* Are we considering any hourly/daily/weekly visualization of data here?
* From EMQTT schema, what metrics we wold be considering to show in visualization as part of API usage monitoring?
* Will we be considering Hourly/Daily/Weekly usage visualizations?

To me the client side monitoring visualization graph is looking more attention grabbing and interesting
https://cloud.githubusercontent.com/assets/2122679/23654223/5d310890-0338-11e7-8aec-5ba59a9ca50e.png
Can we somehow incorporate this sort of visualizations with EMQTT?

2017-03-09 11:50 UTC, frenchbread commented
@Nazarah Thanks for you comments. I've updated def. of done.

> Are we considering any hourly/daily/weekly visualization of data here?

Yes, it is on the way.

> From EMQTT schema, what metrics we wold be considering to show in visualization as part of API usage monitoring?

That is still not decided. 

> Can we somehow incorporate this sort of visualizations with EMQTT?

That's good idea. What exactly are you referring to?

We could actually devide the current (general overview) chart that we have into multiple smaller ones where each chart would represent usage for specific log type (e.g. `on_client_connected`, `on_client_subscribed` etc.) and color them differently.

How does that sound? @bajiat  @brylie @Nazarah

2017-03-09 12:27 UTC, brylie commented
> From EMQTT schema, what metrics we wold be considering to show in visualization as part of API usage monitoring?

@frenchbread can you give us some examples of the types of metrics we might expect? E.g. the name of one or more metric(s) and the data type(s). That way we can at least start sketching some ideas.

2017-03-09 12:31 UTC, frenchbread commented
Here they are https://github.com/apinf/emq-analytics-dashboard/blob/master/dashboard/DATA.md#type-string-possible-options

2017-03-09 12:38 UTC, frenchbread commented
Added granularity filter:

#### By month

![screen shot 2017-03-09 at 14 33 51](https://cloud.githubusercontent.com/assets/2122679/23750500/f1e63fac-04d5-11e7-95ff-255203a282dd.png)

#### By week

![screen shot 2017-03-09 at 14 33 57](https://cloud.githubusercontent.com/assets/2122679/23750505/f89f36f0-04d5-11e7-87c1-62ba6c0039e6.png)

#### By day

![screen shot 2017-03-09 at 14 34 06](https://cloud.githubusercontent.com/assets/2122679/23750511/fee96ca6-04d5-11e7-88e4-cb29076782e5.png)

#### By hour

![screen shot 2017-03-09 at 14 34 13](https://cloud.githubusercontent.com/assets/2122679/23750518/050b3dee-04d6-11e7-9485-9f462b3ed0fc.png)

2017-03-09 14:41 UTC, frenchbread commented
This is what I meant by 

> We could actually devide the current (general overview) chart that we have into multiple smaller ones where each chart would represent usage for specific log type (e.g. on_client_connected, on_client_subscribed etc.) and color them differently.

![screen shot 2017-03-09 at 16 40 55](https://cloud.githubusercontent.com/assets/2122679/23754870/33bc1a6c-04e7-11e7-931d-edbe59499403.png)

2017-03-09 14:48 UTC, frenchbread commented
There are some drawbacks here: 
- When selecting a wide dates range (e.g. 2 years) & granularity `hour` - dashboard freezes

In other cases works fine

2017-03-10 09:47 UTC, brylie commented
Why does the dashboard freeze with large date ranges?

2017-03-10 12:50 UTC, frenchbread commented
I assume it happens due rendering data for large amount of days (> 600 days).

2017-03-10 12:55 UTC, frenchbread commented
`Idea`: we can create use cases for filter queries when dashboard freezes, hide chart and show placeholder message e.g. "Too much data to show" or "Select smaller dates range"..

2017-03-10 13:12 UTC, brylie commented
> I assume it happens due rendering data for large amount of days (> 600 days).

How can you test that hypothesis?

2017-03-10 13:16 UTC, brylie commented
Another idea is to have 'default' granularity settings. E.g. when selecting two years span, defaulting the query to monthly.

2017-03-13 15:08 UTC, frenchbread commented
Removed grid lines & changed datepicker to `pikaday` library

2017-03-14 08:19 UTC, brylie commented
Is this ready for review, or will it be under construction a bit longer?

2017-03-14 12:43 UTC, frenchbread commented
@brylie This is not yet ready.

2017-03-14 14:31 UTC, frenchbread commented
Moved filtering by message type to its own select-picker.

![screen shot 2017-03-14 at 16 26 33](https://cloud.githubusercontent.com/assets/2122679/23905403/a041d97a-08d3-11e7-849c-9c2c25d0cc5d.png)

Please review.

2017-03-15 06:20 UTC, brylie commented
Woohoo! 😀

2017-03-15 12:00 UTC, frenchbread commented
@brylie Could you merge this? If you are going to test it, I can send you ES host with sample data.

2017-03-15 13:00 UTC, brylie requested changes

2017-03-15 13:00 UTC, brylie commented on core/lib/client/pikaday.css
> +@charset "UTF-8";
Is it difficult/impossible to import this CSS from the NPM package?

2017-03-15 13:00 UTC, brylie commented on dashboard/client/index.js
> +    const from = FlowRouter.getQueryParam('from') || moment().subtract(1, 'month').format('YYYY-MM-DD')
Why do we duplicate this here? The FlowRouter `from`, `to`, `granularity`, and `type` query parameters should be set onRender, correct?

2017-03-15 13:00 UTC, brylie commented on dashboard/client/index.js
> +    const from = FlowRouter.getQueryParam('from') || moment().subtract(1, 'month').format('YYYY-MM-DD')
Is there a case where this code is failing without the `||`?

2017-03-15 13:00 UTC, brylie commented on dashboard/client/index.js
> +    // const a = moment(from, 'YYYY-MM-DD')
Clean up commented code.

2017-03-15 13:00 UTC, brylie commented on dashboard/client/index.js
> +    const q = instance.opts.body.query.bool.must
What does `q` refer to? Lets give this variable a semantic name, so we can [avoid mental mapping](https://github.com/ryanmcdermott/clean-code-javascript#avoid-mental-mapping).

2017-03-15 13:00 UTC, brylie commented on dashboard/server/methods.js
> +    // const searches = _.map(types, type => {
Clean up commented code.

2017-03-15 13:00 UTC, brylie commented on dashboard/server/methods.js
> +      console.log(`--------------`)
Clean up console logs.

2017-03-15 13:00 UTC, brylie commented on dashboard/server/methods.js
> +      return [
This function name `getAggr` basically says 'get aggregate data', but we are adding chart style parameters here. [Functions should do one thing](https://github.com/ryanmcdermott/clean-code-javascript#functions-should-do-one-thing), so this function should only return the aggregate data without any chart style rules.

2017-03-15 13:00 UTC, brylie commented on dashboard/server/methods.js
> +  getAggr (opts) {
While this function name pretty much describes what it does, it should also be [meaningful and pronouncable](https://github.com/ryanmcdermott/clean-code-javascript#use-meaningful-and-pronounceable-variable-names). `getAggr` is *almost* meaningful and *sort-of* pronouncable, but would be much better as `getAggregateData`.

2017-03-15 13:00 UTC, brylie commented on dashboard/server/startup.js
>  // import moment from 'moment'
Clean up commented code.

2017-03-15 13:00 UTC, brylie commented on dashboard/server/startup.js
> +// const types = [
Clean up commented code.

2017-03-15 13:00 UTC, brylie commented on dashboard/server/startup.js
> +//     if (randomType === 'on_client_subscribe') {
Clean up commented code.

2017-03-15 13:00 UTC, brylie commented on docs/request-aggregation-metrics.csv
> +Items count,Days amount,Server → ES requrest (ms),ES search exec (ms)
Consider moving this to the `apinf/docs` repository, to a folder containing research and testing related to your EMQ work.

2017-03-15 13:01 UTC, brylie commented
This looks really good from a UI perspective! I made some suggestions on how to improve the code style, so our code conforms to our [developer expectations](https://github.com/apinf/platform/blob/develop/CONTRIBUTING.md#code-quality).

2017-03-15 22:51 UTC, phanimahesh commented
Was this checked with live ES data? If not, @frenchbread let's do a quick check with live data once. First thing tomorrow morning, unless you are occupied. We exchanged docs on event format but still.

2017-03-16 11:24 UTC, frenchbread commented on dashboard/client/index.js
> +    const from = FlowRouter.getQueryParam('from') || moment().subtract(1, 'month').format('YYYY-MM-DD')
There is a case when URL does not contain `from` or `to` params, but we still need to have default date range to request data for.

2017-03-16 12:45 UTC, frenchbread commented
Added suggested changes. Please review

2017-03-16 12:47 UTC, frenchbread commented
After new elasticsearch plugin for emq is deployed, it would require to refactor a little bit in order to fit updated analytics logs schema. But this could be done in separate PR

2017-03-16 12:50 UTC, frenchbread commented
@phanimahesh As we discussed in the chat, yes, dashboard has been tested with live/real ES data. For purposes of testing (with wider date-ranges & collecting metrics of loading/rendering) some dummy data was added in addition to 'real' generated by the plugin.

2017-03-17 08:18 UTC, brylie requested changes

2017-03-17 08:18 UTC, brylie commented on dashboard/client/index.js
> +      Meteor.call('parseDataForNvd', res, (err1, res1) => {
Should this be a Meteor method, or just a client side funciton? I am asking, be cause Meteor methods are mainly server-side (with client side stub). That means, in this scenario, we are getting aggregated data from the server and then sending it back to the server to be parsed and returned again.

2017-03-17 08:18 UTC, brylie commented on dashboard/client/index.js
> +    Meteor.call('parseDataForNvd', data, (err, res) => {
Again, it seems like this parsing step (preparing it for NVD3 should either:

- happen as a sub-function call in the `getChartData` server method
- happen as a client side parsing function

It seems inefficient that we would get data from the server and send it back to the server for further parsing.

2017-03-17 08:18 UTC, brylie commented on dashboard/client/index.js
> +      _.remove(mustQuery, _.find(mustQuery, obj => typeof obj.range !== 'undefined'))
This line of code deserves a human friendly comment.

2017-03-17 08:18 UTC, brylie commented on dashboard/client/index.js
> +    const range = _.find(mustQuery, obj => typeof obj.range !== 'undefined')
Add comment here describing this line of code in plain language.

2017-03-17 08:18 UTC, brylie commented on dashboard/client/index.js
> +    const match = _.find(mustQuery, obj => typeof obj.match !== 'undefined')
Add comment.

2017-03-17 08:18 UTC, brylie commented on dashboard/client/index.js
> +      _.remove(mustQuery, _.find(mustQuery, obj => typeof obj.match !== 'undefined'))
Add comment.

2017-03-20 11:06 UTC, frenchbread commented on dashboard/client/index.js
> +      Meteor.call('parseDataForNvd', res, (err1, res1) => {
This is a server-side method created to decrease the load on client-site (browser).

> That means, in this scenario, we are getting aggregated data from the server and then sending it back to the server to be parsed and returned again.

Right.

2017-03-20 11:12 UTC, brylie commented on dashboard/client/index.js
> +      Meteor.call('parseDataForNvd', res, (err1, res1) => {
I think we should reduce the number of round trips. If we want to decrease the client load by performing a second aggregation on the server, then send the data only **after** it has been aggregated properly.

2017-03-20 11:14 UTC, frenchbread commented
Added comments

2017-03-20 13:33 UTC, frenchbread commented
Removed second meteor method. Please :mag_right:

2017-03-21 11:08 UTC, merged